name: incubyte_tdd_assignment
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
